import Header from '@/components/Header'
import '../globals.css'
import type { Metadata } from 'next'
import Banner from '@/components/Banner'


export const metadata: Metadata = {
  title: 'Blog App | OutBreak',
  description: 'Generated by Nikhil Mishra',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='max-w-6xl mx-auto'>
      <Header />
      <Banner />
        {children}</body>
    </html>
  )
}
